#!/usr/bin/env python3
"""Independent integer audits of the nine coefficient rows at 22*s^2.
Not a tiling search. Conditional geometric conclusions require the written
exhaustive spectra and prime-power stabilization theorem.
"""
import argparse
import json
from math import gcd,isqrt
from pathlib import Path

if not __debug__:
 raise SystemExit('Run with ordinary Python; -O disables the exact checks.')

def prime(n):
 return n>=2 and all(n%p for p in range(2,isqrt(n)+1))
def divisors(n):
 small=[d for d in range(1,isqrt(n)+1) if n%d==0]
 return sorted(set(small+[n//d for d in small]))
def square(n):
 return n>=0 and isqrt(n)**2==n

def inverse(D):
 hits=set()
 for B in divisors(D):
  Q=D//B
  v2,u2=Q-B,Q-2*B
  if u2>0 and square(u2) and square(v2):
   u,v=isqrt(u2),isqrt(v2)
   if u<v and gcd(u,v)==1:hits.add(('alpha',u,v))
  P=Q;Q=B
  v2,u2=P-Q,2*P-3*Q
  if u2>0 and square(u2) and square(v2):
   u,v=isqrt(u2),isqrt(v2)
   if u<v and gcd(u,v)==1:hits.add(('QP',u,v))
 def norm(label,a,b,sign=1):
  if a<=0 or b<=0 or gcd(a,b)!=1:return
  c2=a*a+sign*a*b+b*b
  if square(c2):hits.add((label,a,b,isqrt(c2)))
 for x in divisors(D):
  y=D//x
  norm('E60',x,y,-1);norm('E120',x,y)
  norm('F1',y-x,x);norm('I120',y-2*x,x)
  if (2*y-x)%3==0 and (2*x-y)%3==0:
   norm('F2',(2*y-x)//3,(2*x-y)//3)
  norm('F4',y-x,2*x-y)
 if D%3==0:
  for x in divisors(D//3):
   y=D//(3*x)
   norm('F3',2*x-y,y-x)
 return hits

def independent_generation(limit):
 """Complete conic parametrization and bounded u,v; no divisor inversions.

 For Group1, bQ>v^3 and QP>2v^4, so v^3<=limit is a complete bound.
 Every ordered primitive positive plus-norm triple is generated by
 k/2<h<k, gcd(h,k)=1 and the displayed formula, with common gcd g in
 {1,3}. Writing delta=k-h and epsilon=2h-k gives
 ab=delta*epsilon*k*(k+h)/g^2 >= k^3/27. Every norm-row coefficient
 is at least ab, so k^3<=27*limit is a complete, input-derived bound.
 For minus norm x>=y, (x-y,y,c) is a plus-norm triple with product
 <=xy; the sole x=y primitive case is (1,1,1), added separately.
 Thus this comparison has no empirically selected tile-side cutoff.
 """
 out={}
 def put(D,item):
  if D<=limit:out.setdefault(D,set()).add(item)
 for v in range(2,limit+1):
  if v**3>limit:break
  for u in range(1,v):
   if gcd(u,v)!=1:continue
   b=v*v-u*u;Q=2*v*v-u*u;P=3*v*v-u*u
   put(b*Q,('alpha',u,v));put(Q*P,('QP',u,v))
 plus=set()
 # From ab>=k^3/27 in the complete primitive parametrization.
 for k in range(2,limit+1):
  if k**3>27*limit:break
  for h in range(k//2+1,k):
   if gcd(h,k)!=1:continue
   aa=k*k-h*h;bb=k*(2*h-k);cc=h*h-h*k+k*k
   g=gcd(gcd(aa,bb),cc)
   assert g in (1,3)
   a,b,c=aa//g,bb//g,cc//g
   assert gcd(a,b)==1 and a*a+a*b+b*b==c*c
   if a*b<=limit:plus.add((a,b,c))
 for a,b,c in plus:
  for x,y in {(a,b),(b,a)}:
   forms=[('E120',x*y),('F1',y*(x+y)),('I120',y*(x+2*y)),
          ('F2',(x+2*y)*(2*x+y)),('F3',3*(x+2*y)*(x+y)),
          ('F4',(2*x+y)*(x+y))]
   for label,D in forms:put(D,(label,x,y,c))
  # Every non-equilateral minus norm is obtained by adding the sides of
  # a plus norm. Ordered choices below cover both possible reductions.
  for x,y in {(a+b,a),(a,a+b),(a+b,b),(b,a+b)}:
   assert x*x-x*y+y*y==c*c
   put(x*y,('E60',x,y,c))
 put(1,('E60',1,1,1))
 return out

def check():
 powers={1}
 prime_power_labels={1:None}
 for q in range(3,45,2):
  if not prime(q):continue
  s=q;r=1
  while s<=44:
   powers.add(s);prime_power_labels[s]=[q,r]
   s*=q;r+=1
 Ds=[22*s*s for s in sorted(powers)]
 generated=independent_generation(max(Ds))
 checks=[]
 for s,D in zip(sorted(powers),Ds):
  a=inverse(D);b=generated.get(D,set())
  assert a==b,(s,D,a,b)
  checks.append({'s':s,'prime_power':prime_power_labels[s],'coefficient':D,'hits':[list(x) for x in sorted(a)]})
 assert all(not x['hits'] for x in checks)
 # A broader comparison catches inverse formula/side-order errors, cheaply.
 for D in range(1,5001):assert inverse(D)==generated.get(D,set()),D
 m=248599631
 fac={7:1,3089:1,11497:1}
 assert all(prime(p) for p in fac)
 assert 7*3089*11497==m
 u,v=10132,22779
 Q=2*v*v-u*u;P=3*v*v-u*u
 assert gcd(u,v)==1 and 0<u<v and Q*P==22*m*m
 assert Q==2*(7*3089)**2 and P==11*11497**2
 report={'status':'PASS','scope':'nine necessary coefficient rows; not a tiling existence search',
         'd':22,'s_max':44,'cases':checks,
         'independent_methods':['divisor inversion','complete conic parametrization and bounded Group1 parameter generation'],
         'cross_comparison_coefficients':[1,5000],
         'completeness_bounds':{'group1':'v^3 <= coefficient limit',
           'plus_norm':'k^3 <= 27 * coefficient limit',
           'minus_norm':'reduce (x,y) to plus norm (x-y,y), apart from (1,1,1)'},
         'old_positive_witness':{'u':u,'v':v,'Q':Q,'P':P,'m':m,'m_factorization':fac,'N':22*m*m,
           'scope':'Arithmetic identity rechecked here; geometric construction was certified in the earlier uniform-sectors package.'}}
 return report


def main():
 parser=argparse.ArgumentParser(description=__doc__)
 parser.add_argument('--report',type=Path,help='Optionally save the deterministic JSON report.')
 args=parser.parse_args()
 report=check()
 if args.report:
  args.report.write_text(json.dumps(report,indent=2)+'\n')
 print(json.dumps(report,indent=2))


if __name__=='__main__':main()
