// Exact fixed-denominator frontier search for the 154 I120 candidate.
// A resource limit means INCOMPLETE, never a negative certificate.
#include <algorithm>
#include <array>
#include <chrono>
#include <climits>
#include <cmath>
#include <cstdint>
#include <deque>
#include <fstream>
#include <iostream>
#include <limits>
#include <map>
#include <numeric>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
#include "inventory_completion.hpp"
using namespace std;
using I=__int128_t; using L=int64_t;
constexpr L D=1792160394037LL; // 13^11
constexpr int N=154;
struct P{L x,y; bool operator==(const P&b)const{return x==b.x&&y==b.y;} bool operator!=(const P&b)const{return !(*this==b);} bool operator<(const P&b)const{return x<b.x||(x==b.x&&y<b.y);}};
struct PH{size_t operator()(const P&p)const{return hash<L>{}(p.x)^(hash<L>{}(p.y)+0x9e3779b97f4a7c15ULL+(hash<L>{}(p.x)<<6));}};
P operator+(P a,P b){return {a.x+b.x,a.y+b.y};} P operator-(P a,P b){return {a.x-b.x,a.y-b.y};}
P operator*(P a,L n){return {a.x*n,a.y*n};}
I cross(P a,P b){return I(a.x)*b.y-I(a.y)*b.x;}
I norm(P a){return I(a.x)*a.x+I(a.x)*a.y+I(a.y)*a.y;}
P normal(P a){L g=gcd(a.x,a.y);if(!g)throw runtime_error("zero direction");return {a.x/g,a.y/g};}
I gcd128(I a,I b){if(a<0)a=-a;if(b<0)b=-b;while(b){I t=a%b;a=b;b=t;}return a;}
pair<I,I> product_normal(P u,P v){I a=I(u.x)*v.x-I(u.y)*v.y,b=I(u.x)*v.y+I(u.y)*v.x+I(u.y)*v.y;I g=gcd128(a,b);return {a/g,b/g};}
P conj(P a){return {a.x+a.y,-a.y};}
P rot(P a){return {-a.y,a.x+a.y};}
int half(P a){return (a.y>0||(a.y==0&&a.x>0))?0:1;}
bool argless(P a,P b){return half(a)!=half(b)?half(a)<half(b):cross(a,b)>0;}
P smallproduct(P a,P b){auto p=product_normal(a,b);if(p.first<LLONG_MIN||p.first>LLONG_MAX||p.second<LLONG_MIN||p.second>LLONG_MAX)throw runtime_error("small angle overflow");return {(L)p.first,(L)p.second};}
string istr(I x){if(x==0)return "0";bool neg=x<0;if(neg)x=-x;string s;while(x){s.push_back(char('0'+x%10));x/=10;}if(neg)s.push_back('-');reverse(s.begin(),s.end());return s;}
vector<P> pts; unordered_map<P,int,PH> pids;
int point(P p){auto it=pids.find(p);if(it!=pids.end())return it->second;int i=pts.size();pts.push_back(p);pids[p]=i;return i;}
I orient(int a,int b,int c){return cross(pts[b]-pts[a],pts[c]-pts[a]);}
P direction(int a,int b){return normal(pts[b]-pts[a]);}
bool integral(P d){I n=norm(d),s2=I(D)*D;if(n%s2)return false;I q=n/s2;L s=(L)sqrtl((long double)q);while(I(s)*s<q)++s;while(I(s)*s>q)--s;return I(s)*s==q;}
array<int,3> OUT; bool sem[155];
bool inside(P p){return p.y>=0&&I(8)*p.x>=I(7)*p.y&&I(8)*p.x+I(15)*p.y<=I(1232)*D;}
vector<pair<int,int>> positions(P p){vector<pair<int,int>> out;auto add=[&](int k,I num,I den){if(num%den){out.emplace_back(k,-1);return;}I s=num/den;out.emplace_back(k,s>=0&&s<=154?(int)s:-1);};if(p.y==0)add(0,p.x,D);if(I(8)*p.x+I(15)*p.y==I(1232)*D)add(1,I(13)*p.y,I(8)*D);if(I(8)*p.x-I(7)*p.y==0)add(2,I(13)*p.y,I(8)*D);return out;}
bool vertexok(P p){if(!inside(p))return false;for(auto [k,s]:positions(p)){int len=k?91:154;if(s<0||s>len||!sem[s]||!sem[len-s])return false;}return true;}
bool onseg(int p,int q,int v){P a=pts[p],b=pts[q],c=pts[v];return !cross(b-a,c-a)&&min(a.x,b.x)<=c.x&&c.x<=max(a.x,b.x)&&min(a.y,b.y)<=c.y&&c.y<=max(a.y,b.y);}
struct T{array<int,3> v;array<L,4> box;int h,group;vector<int> marks;vector<pair<int,int>> ces;array<vector<int>,3> bp;};
vector<T> tri;map<array<int,3>,int> tids;
int triangle(array<int,3> v,int h,int group){if(orient(v[0],v[1],v[2])<0)swap(v[1],v[2]);int first=0;for(int j=1;j<3;++j)if(pts[v[j]]<pts[v[first]])first=j;v={v[first],v[(first+1)%3],v[(first+2)%3]};auto it=tids.find(v);if(it!=tids.end()){if(tri[it->second].h!=h)throw runtime_error("height mismatch");return it->second;}T t;t.v=v;t.h=h;t.group=group;t.box={pts[v[0]].x,pts[v[0]].x,pts[v[0]].y,pts[v[0]].y};for(int j=0;j<3;++j){int p=v[j],q=v[(j+1)%3],r=v[(j+2)%3];t.box[0]=min(t.box[0],pts[p].x);t.box[1]=max(t.box[1],pts[p].x);t.box[2]=min(t.box[2],pts[p].y);t.box[3]=max(t.box[3],pts[p].y);for(auto[k,s]:positions(pts[p])){if(s<0)throw runtime_error("nonintegral boundary vertex");t.bp[k].push_back(s);}if(norm(pts[q]-pts[r])==I(169)*D*D){bool marked=false,ce=false;for(int k=0;k<3;++k){int a=OUT[k],b=OUT[(k+1)%3];marked|=orient(a,b,p)==0&&(orient(a,b,q)==0||orient(a,b,r)==0);ce|=orient(a,b,q)==0&&orient(a,b,r)==0;}if(marked)t.marks.push_back(p);if(ce)t.ces.push_back({q,r});}}int id=tri.size();tri.push_back(t);tids[v]=id;return id;}
unordered_map<uint64_t,bool> incache;uint64_t pairkey(int a,int b){if(a>b)swap(a,b);return (uint64_t(uint32_t(a))<<32)|uint32_t(b);}
bool incompatible_uncached(int a,int b){if(a==b)return true;T aa=tri[a],bb=tri[b];if(aa.box[1]<bb.box[0]||bb.box[1]<aa.box[0]||aa.box[3]<bb.box[2]||bb.box[3]<aa.box[2])return false;bool sep=false;for(int turn=0;turn<2;++turn){const auto &t=turn?bb.v:aa.v,&u=turn?aa.v:bb.v;for(int j=0;j<3;++j)if(all_of(u.begin(),u.end(),[&](int v){return orient(t[j],t[(j+1)%3],v)<=0;}))sep=true;}if(!sep)return true;for(int turn=0;turn<2;++turn){const auto&t=turn?bb.v:aa.v,&u=turn?aa.v:bb.v;for(int v:t)for(int j=0;j<3;++j){int p=u[j],q=u[(j+1)%3];if(v!=p&&v!=q&&onseg(p,q,v)&&!integral(pts[v]-pts[p]))return true;}}return false;}
bool incompatible(int a,int b){auto k=pairkey(a,b);auto it=incache.find(k);if(it!=incache.end())return it->second;bool z=incompatible_uncached(a,b);if(incache.size()>3000000)incache.clear();incache[k]=z;return z;}
using Fan=vector<int>;using Boundary=vector<pair<int,int>>;using Gap=array<int,3>;
Fan united(Fan a,const Fan&b){a.insert(a.end(),b.begin(),b.end());sort(a.begin(),a.end());a.erase(unique(a.begin(),a.end()),a.end());return a;}
int elementary(const Fan&ts){array<int,23> cnt{};int lo=0,hi=0;for(int t:ts){int h=tri[t].h;if(h< -11||h>11)return 1;cnt[h+11]++;lo=min(lo,h);hi=max(hi,h);}if(hi-lo>4)return 1;int needed=24+13*max(0,(cnt[11]-24+12)/13);for(int h=lo;h<=hi;++h)if(h)needed+=13*max(2,(cnt[h+11]+12)/13);if(needed>154)return 1;set<int> marked(OUT.begin(),OUT.end());vector<pair<int,int>> ces;array<set<int>,3> bp;bp[0]={0,154};bp[1]=bp[2]={0,91};for(int t:ts){for(int v:tri[t].marks)marked.insert(v);ces.insert(ces.end(),tri[t].ces.begin(),tri[t].ces.end());for(int k=0;k<3;++k)bp[k].insert(tri[t].bp[k].begin(),tri[t].bp[k].end());}for(auto[p,q]:ces)if(marked.count(p)&&marked.count(q))return 2;for(int k=0;k<3;++k){int last=-1;for(int s:bp[k]){if(last>=0&&!sem[s-last])return 3;last=s;}}return 0;}
Boundary addtiles(const Boundary&boundary,const Fan&added){set<int> nv,ov;for(int t:added)for(int v:tri[t].v)nv.insert(v);for(auto[p,q]:boundary){ov.insert(p);ov.insert(q);}set<int> all=nv;all.insert(ov.begin(),ov.end());map<pair<int,int>,int> counts;auto insert=[&](int p,int q,const set<int>&pool){vector<int> cuts{p,q};for(int v:pool)if(v!=p&&v!=q&&onseg(p,q,v))cuts.push_back(v);sort(cuts.begin(),cuts.end(),[&](int a,int b){return pts[a]<pts[b];});cuts.erase(unique(cuts.begin(),cuts.end()),cuts.end());if(pts[q]<pts[p])reverse(cuts.begin(),cuts.end());for(size_t j=1;j<cuts.size();++j){int a=cuts[j-1],b=cuts[j];if(a<b)counts[{a,b}]++;else counts[{b,a}]--;}};for(auto[p,q]:boundary)insert(p,q,nv);for(int t:added){auto v=tri[t].v;for(int j=0;j<3;++j)insert(v[(j+1)%3],v[j],all);}Boundary out;for(auto[e,n]:counts){if(abs(n)>1)throw runtime_error("boundary multiplicity");if(n)out.push_back(n>0?e:make_pair(e.second,e.first));}sort(out.begin(),out.end());return out;}
set<pair<I,I>> anglemap;
bool angleok(P start,P end){return anglemap.count(product_normal(end,conj(start)));}
int boundaryinfo(const Boundary&b,vector<Gap>&gaps){map<int,vector<int>> outgoing,incoming;for(auto[p,q]:b){if(!integral(pts[q]-pts[p]))return 4;outgoing[p].push_back(q);incoming[q].push_back(p);}bool simple=true;for(auto&[v,qq]:outgoing){if(qq.size()==1&&incoming[v].size()==1){int q=qq[0],p=incoming[v][0];if(!angleok(direction(v,q),direction(v,p)))return 5;if(orient(p,v,q)>0)gaps.push_back({v,q,p});}else simple=false;}for(auto&[v,ps]:incoming)if(ps.size()!=1)simple=false;if(simple){set<int> unused;for(auto&[v,q]:outgoing)unused.insert(v);vector<I> areas;while(!unused.empty()){int s=*unused.begin(),v=s;I area=0;do{if(!unused.erase(v))throw runtime_error("bad cycle");int w=outgoing[v][0];area+=cross(pts[v],pts[w]);v=w;}while(v!=s);areas.push_back(area);}if(!areas.empty()&&all_of(areas.begin(),areas.end(),[](I a){return a>0;}))for(I a:areas)if(a%(I(56)*D*D))return 6;}sort(gaps.begin(),gaps.end(),[](Gap a,Gap b){return pts[a[0]].y!=pts[b[0]].y?pts[a[0]].y<pts[b[0]].y:pts[a[0]].x<pts[b[0]].x;});return 0;}
struct Template{P u,v;int h,group;};map<P,vector<Template>> templates;
struct Cand{int t;P next;};unordered_map<string,vector<Cand>> candcache;
template<class V> void appendbin(string&s,const V&v){s.append(reinterpret_cast<const char*>(&v),sizeof(v));}
vector<Cand> candidates(int v,P dir){string key;appendbin(key,v);appendbin(key,dir.x);appendbin(key,dir.y);auto it=candcache.find(key);if(it!=candcache.end())return it->second;vector<Cand> out;auto jt=templates.find(dir);if(jt!=templates.end())for(auto t:jt->second){P a=pts[v]+t.u,b=pts[v]+t.v;if(vertexok(a)&&vertexok(b)){int p=point(a),q=point(b);out.push_back({triangle({v,p,q},t.h,t.group),normal(t.v)});}}candcache[key]=out;return out;}
unordered_map<string,vector<Fan>> rawcache;
vector<Fan> rawfans(int v,P start,P end,const Fan&near){string key;appendbin(key,v);appendbin(key,start.x);appendbin(key,start.y);appendbin(key,end.x);appendbin(key,end.y);for(int t:near)appendbin(key,t);auto it=rawcache.find(key);if(it!=rawcache.end())return it->second;set<Fan> out;Fan placed;auto grow=[&](auto&&self,P current)->void{if(current==end){Fan f=placed;sort(f.begin(),f.end());out.insert(f);return;}for(auto c:candidates(v,current)){if(c.next!=end&&(cross(start,c.next)<=0||cross(c.next,end)<=0))continue;bool bad=false;for(int t:near)if(incompatible(c.t,t)){bad=true;break;}if(bad)continue;for(int t:placed)if(incompatible(c.t,t)){bad=true;break;}if(bad)continue;placed.push_back(c.t);self(self,c.next);placed.pop_back();}};grow(grow,start);vector<Fan> r(out.begin(),out.end());if(rawcache.size()>100000)rawcache.clear();rawcache[key]=r;return r;}
vector<Fan> fans(Gap gap,const Fan&ts){P p=pts[gap[0]];Fan near;for(int t:ts){auto b=tri[t].box;if(b[1]>=p.x-16*D&&b[0]<=p.x+16*D&&b[3]>=p.y-16*D&&b[2]<=p.y+16*D)near.push_back(t);}auto out=rawfans(gap[0],direction(gap[0],gap[1]),direction(gap[0],gap[2]),near);out.erase(remove_if(out.begin(),out.end(),[&](const Fan&f){return elementary(united(ts,f));}),out.end());return out;}
bool compatible(const Fan&a,const Fan&b){for(int t:a)for(int u:b)if(t!=u&&incompatible(t,u))return false;return true;}
int propagate(const vector<Gap>&gaps,const Fan&ts,vector<vector<Fan>>&ds){for(auto g:gaps){ds.push_back(fans(g,ts));if(ds.back().empty())return 7;}int n=gaps.size();vector<vector<int>> near(n);for(int i=0;i<n;++i)for(int j=0;j<n;++j)if(i!=j){P a=pts[gaps[i][0]],b=pts[gaps[j][0]];if(llabs(a.x-b.x)<=32*D&&llabs(a.y-b.y)<=32*D)near[i].push_back(j);}while(true){deque<pair<int,int>> todo;for(int i=0;i<n;++i)for(int j:near[i])todo.push_back({i,j});while(!todo.empty()){auto[i,j]=todo.front();todo.pop_front();vector<Fan> out;for(auto&f:ds[i])if(any_of(ds[j].begin(),ds[j].end(),[&](const Fan&h){return compatible(f,h);}))out.push_back(f);if(out.size()<ds[i].size()){if(out.empty())return 8;ds[i]=move(out);for(int k:near[i])if(k!=j)todo.push_back({k,i});}}vector<int> bin;for(int i=0;i<n;++i)if(ds[i].size()==2)bin.push_back(i);int sz=2*bin.size(),words=(sz+63)/64;vector<vector<uint64_t>> reach(sz,vector<uint64_t>(words));auto edge=[&](int a,int b){reach[a][b/64]|=1ULL<<(b%64);};for(int i=0;i<sz;++i)edge(i,i);for(int x=0;x<(int)bin.size();++x)for(int y=x+1;y<(int)bin.size();++y){int i=bin[x],j=bin[y];if(find(near[i].begin(),near[i].end(),j)==near[i].end())continue;for(int a=0;a<2;++a)for(int b=0;b<2;++b)if(!compatible(ds[i][a],ds[j][b])){edge(2*x+a,2*y+1-b);edge(2*y+b,2*x+1-a);}}for(int k=0;k<sz;++k)for(int i=0;i<sz;++i)if(reach[i][k/64]&(1ULL<<(k%64)))for(int w=0;w<words;++w)reach[i][w]|=reach[k][w];bool forced=false;for(int x=0;x<(int)bin.size();++x){int a=2*x,b=a+1;bool bad0=reach[a][b/64]&(1ULL<<(b%64)),bad1=reach[b][a/64]&(1ULL<<(a%64));if(bad0&&bad1)return 9;if(bad0){ds[bin[x]]={ds[bin[x]][1]};forced=true;}else if(bad1){ds[bin[x]]={ds[bin[x]][0]};forced=true;}}if(!forced)return 0;}}
string statekey(const Fan&ts){string k;for(int t:ts)appendbin(k,t);return k;}
struct Search{chrono::steady_clock::time_point start=chrono::steady_clock::now();double limit;uint64_t nodes=0,cap;int maxdepth=0;map<int,uint64_t> rejects;unordered_set<string> dead;Fan solution;ofstream trace;bool timed=false;Search(double sec,uint64_t nc,const string&path):limit(sec),cap(nc),trace(path){}double elapsed(){return chrono::duration<double>(chrono::steady_clock::now()-start).count();}void record(const Fan&ts,int rule){string k=statekey(ts);dead.insert(k);if(trace){trace<<rule;for(int t:ts)trace<<' '<<t;trace<<'\n';}}bool run(const Fan&ts,const Boundary&b){if(dead.count(statekey(ts)))return false;if(ts.size()==154){if(!b.empty())throw runtime_error("full count nonempty boundary");solution=ts;return true;}if(ts.size()>154){record(ts,10);return false;}if(nodes>=cap||elapsed()>=limit){timed=true;throw runtime_error("RESOURCE_LIMIT");}++nodes;maxdepth=max(maxdepth,(int)ts.size());if(nodes%1000==0)cerr<<"nodes "<<nodes<<" depth "<<ts.size()<<" max "<<maxdepth<<" seconds "<<elapsed()<<" triangles "<<tri.size()<<" dead "<<dead.size()<<'\n';int er=elementary(ts);if(er){rejects[er]++;record(ts,er);return false;}erdos154_inventory::Groups populations{};for(int t:ts)populations[tri[t].h+11][tri[t].group]++;if(!erdos154_inventory::completion(populations)){rejects[14]++;record(ts,14);return false;}vector<Gap> gaps;er=boundaryinfo(b,gaps);if(er){rejects[er]++;record(ts,er);return false;}vector<vector<Fan>> ds;er=propagate(gaps,ts,ds);if(er){rejects[er]++;record(ts,er);return false;}if(ds.empty())throw runtime_error("NO_CONVEX_GAP");Fan forced;for(auto&d:ds)if(d.size()==1)forced=united(forced,d[0]);Fan added;set_difference(forced.begin(),forced.end(),ts.begin(),ts.end(),back_inserter(added));if(!added.empty()){Fan nxt=united(ts,added);bool yes=run(nxt,addtiles(b,added));if(!yes)record(ts,11);return yes;}int choice=0;for(int i=1;i<(int)ds.size();++i){auto key=[&](int j){int mini=1000;for(auto&f:ds[j])mini=min(mini,(int)f.size());return tuple<size_t,L,int>(ds[j].size(),-pts[gaps[j][0]].y,-mini);};if(key(i)<key(choice))choice=i;}for(auto&f:ds[choice]){Fan more;set_difference(f.begin(),f.end(),ts.begin(),ts.end(),back_inserter(more));if(more.empty())throw runtime_error("nonincreasing branch");if(run(united(ts,f),addtiles(b,more)))return true;}record(ts,12);return false;}};
void setup(){L d=1;for(int i=0;i<11;++i)d*=13;if(d!=D)throw runtime_error("D wrong");for(int a=0;a<=22;++a)for(int b=0;b<=19;++b)for(int c=0;c<=11;++c)if(7*a+8*b+13*c<=154)sem[7*a+8*b+13*c]=true;OUT={point({0,0}),point({154*D,0}),point({49*D,56*D})};P u{1,0};while(true){P v=u;while(true){if(!(v==P{1,0}))anglemap.insert({v.x,v.y});P z=smallproduct(v,{8,7});if(!argless(v,z))break;v=z;}P z=smallproduct(u,{7,8});if(!argless(u,z))break;u=z;}map<int,P> units;units[0]={D,0};for(int sign:{-1,1}){P p{D,0};for(int h=1;h<=11;++h){P m=sign==1?P{8,7}:P{15,-7};I x=I(p.x)*m.x-I(p.y)*m.y,y=I(p.x)*m.y+I(p.y)*m.x+I(p.y)*m.y;if(x%13||y%13)throw runtime_error("unit denominator");p={(L)(x/13),(L)(y/13)};if(norm(p)!=I(D)*D)throw runtime_error("unit norm");units[sign*h]=p;}}for(auto[h,p]:units)for(int order=0;order<2;++order){P a=p*(order?7:8),b=rot(rot(p))*(order?8:7);for(int r=0;r<6;++r){array<P,3> vs{P{0,0},a,b};if(cross(a,b)!=I(56)*D*D)throw runtime_error("template area");for(int j=0;j<3;++j){P x=vs[(j+1)%3]-vs[j],y=vs[(j+2)%3]-vs[j];templates[normal(x)].push_back({x,y,h,order?(r%2?0:1):(r%2?3:2)});}a=rot(a);b=rot(b);}}}
int main(int argc,char**argv){try{double seconds=argc>1?stod(argv[1]):1800;uint64_t cap=argc>2?stoull(argv[2]):100000000;string prefix=argc>3?argv[3]:"search154";setup();cerr<<"D "<<D<<" directions "<<templates.size()<<" angletypes "<<anglemap.size()<<'\n';Search s(seconds,cap,prefix+"-trace.txt");string status;Boundary b{{OUT[0],OUT[1]},{OUT[1],OUT[2]},{OUT[2],OUT[0]}};try{status=s.run({},b)?"TILING_CANDIDATE":"EXHAUSTED_REQUIRES_INDEPENDENT_REPLAY";}catch(const runtime_error&e){if(string(e.what())=="RESOURCE_LIMIT")status="INCOMPLETE";else throw;}ofstream f(prefix+"-report.json");f<<"{\n\"status\":\""<<status<<"\",\n\"nodes\":"<<s.nodes<<",\n\"seconds\":"<<s.elapsed()<<",\n\"maximum_depth\":"<<s.maxdepth<<",\n\"generated_triangles\":"<<tri.size()<<",\n\"dead_states\":"<<s.dead.size()<<",\n\"height_bound\":[-11,11],\n\"root\":\"empty; every convex-corner fan is covered\",\n\"N154_decided\":false,\n\"full_Erdos634_solved\":false,\n\"rejections\":{";bool comma=false;for(auto[k,n]:s.rejects){if(comma)f<<',';comma=true;f<<'"'<<k<<"\":"<<n;}f<<"},\n\"solution\":[";for(size_t i=0;i<s.solution.size();++i){if(i)f<<',';f<<'[';for(int j=0;j<3;++j){if(j)f<<',';P p=pts[tri[s.solution[i]].v[j]];f<<"[\""<<p.x<<'/'<<D<<"\",\""<<p.y<<'/'<<D<<"\"]";}f<<']';}f<<"]\n}\n";ofstream geom(prefix+"-geometry.txt");geom<<D<<' '<<pts.size()<<' '<<tri.size()<<'\n';for(P p:pts)geom<<p.x<<' '<<p.y<<'\n';for(auto&t:tri)geom<<t.v[0]<<' '<<t.v[1]<<' '<<t.v[2]<<' '<<t.h<<' '<<t.group<<'\n';cerr<<status<<" nodes="<<s.nodes<<" seconds="<<s.elapsed()<<" maxdepth="<<s.maxdepth<<'\n';return 0;}catch(const exception&e){cerr<<"ERROR "<<e.what()<<'\n';return 1;}}
